//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email pertence a uma conta já existente..
        /// </summary>
        public static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil cadastrado..
        /// </summary>
        public static string CreateAccountOk {
            get {
                return ResourceManager.GetString("CreateAccountOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0 } Peças salvas..
        /// </summary>
        public static string CreateMultiplePieceOk {
            get {
                return ResourceManager.GetString("CreateMultiplePieceOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peça salva..
        /// </summary>
        public static string CreatePieceOk {
            get {
                return ResourceManager.GetString("CreatePieceOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailField {
            get {
                return ResourceManager.GetString("EmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email e email de confirmação são diferentes..
        /// </summary>
        public static string EmailNotEqualsConfirmation {
            get {
                return ResourceManager.GetString("EmailNotEqualsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar as entidades {0}..
        /// </summary>
        public static string EntityNotFoundMultiple {
            get {
                return ResourceManager.GetString("EntityNotFoundMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar a entidade {0}..
        /// </summary>
        public static string EntityNotFoundSingle {
            get {
                return ResourceManager.GetString("EntityNotFoundSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar arquivo {0}..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ou senha incorretos..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ser maior que {1}..
        /// </summary>
        public static string MinLengthError {
            get {
                return ResourceManager.GetString("MinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string NameField {
            get {
                return ResourceManager.GetString("NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha e senha de confirmação são diferentes..
        /// </summary>
        public static string PasswordNotEqualsConfirmation {
            get {
                return ResourceManager.GetString("PasswordNotEqualsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Peças removidas..
        /// </summary>
        public static string RemoveMultiplePieceOk {
            get {
                return ResourceManager.GetString("RemoveMultiplePieceOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peça removida..
        /// </summary>
        public static string RemovePieceOk {
            get {
                return ResourceManager.GetString("RemovePieceOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código não encontrado..
        /// </summary>
        public static string SecredCodeNotFound {
            get {
                return ResourceManager.GetString("SecredCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código expirado..
        /// </summary>
        public static string SecretCodeExpired {
            get {
                return ResourceManager.GetString("SecretCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código já foi usado..
        /// </summary>
        public static string SecretCodeUnavailable {
            get {
                return ResourceManager.GetString("SecretCodeUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil atualizado..
        /// </summary>
        public static string UpdateAccountOk {
            get {
                return ResourceManager.GetString("UpdateAccountOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peça atulizada..
        /// </summary>
        public static string UpdatePieceOk {
            get {
                return ResourceManager.GetString("UpdatePieceOk", resourceCulture);
            }
        }
    }
}
